### ISSUE TITLE
Integrate innocraft/php-experiments?

### ISSUE THREAD

**Issue by simonschaufi** [wysiwyg-software-design/Wysiwyg.ABTesting#2]
Hi, I just want to make you aware of the package https://github.com/innocraft/php-experiments. Maybe it's useful to integrate that into this package?

**Comment by svwu** [comment]
Hello @simonschaufi 
This package offers a A/B Testing based on the flow framework with all workflows.
Integrating this package doesn't apply these workflows.

Plus we do want to give the project the choice of the tracking system which will be used for measure the tests. It has a highly dependency to Matomo.

Best,
Sven

**Comment by simonschaufi** [comment]
Hi Sven, they write that php-experiments can be used standalone as well but yeah, I totally got your point of view. Anyway, you can still be inspired by the project ;)
