### ISSUE TITLE
Use cache mode `dynamic` instead of uncached

### ISSUE THREAD

**Issue by mficzel** [wysiwyg-software-design/Wysiwyg.ABTesting#6]
Currently the content of ab testing containers is `uncached` which can lead to performance problems. 

Using cache mode  `dynamic` with a `discriminator` to make a distinction between the three cases could improve this.

**Comment by breadlesscode** [comment]
I will configure the cache next week :) Thanks for your feedback

**Comment by svwu** [comment]
We have had the container cached once, but it lead to unwanted behaviour.
We should check it in detail

**Comment by breadlesscode** [comment]
I fixed it. Thank you @mficzel for your hint :+1:

https://github.com/wysiwyg-software-design/Wysiwyg.ABTesting/blob/master/Resources/Private/Fusion/NodeTypes/ABTestingContainer.fusion#L18-L40
